export const DOG_BREEDS = [
  'Mestizo / Criollo',
  'No sé / No aplica',
  'Affenpinscher',
  'Airedale Terrier',
  'Akita',
  'Alaskan Malamute',
  'American Bully',
  'American Staffordshire Terrier',
  'Australian Cattle Dog',
  'Australian Shepherd',
  'Basenji',
  'Basset Hound',
  'Beagle',
  'Bearded Collie',
  'Bernés de la Montaña',
  'Bichón Frisé',
  'Bichón Maltés',
  'Border Collie',
  'Boston Terrier',
  'Boxer',
  'Boyero de Berna',
  'Braco Alemán',
  'Bretón Español',
  'Bull Terrier',
  'Bulldog Francés',
  'Bulldog Inglés',
  'Cairn Terrier',
  'Cane Corso',
  'Caniche / Poodle',
  'Chihuahua',
  'Chow Chow',
  'Cocker Spaniel',
  'Collie',
  'Corgi Galés Cardigan',
  'Corgi Galés Pembroke',
  'Dachshund / Salchicha',
  'Dálmata',
  'Doberman',
  'Dogo Argentino',
  'Dogo de Burdeos',
  'English Springer Spaniel',
  'Fox Terrier',
  'Galgo',
  'Golden Retriever',
  'Gran Danés',
  'Husky Siberiano',
  'Jack Russell Terrier',
  'Labradoodle',
  'Labrador Retriever',
  'Lhasa Apso',
  'Mastín Español',
  'Mastín Inglés',
  'Pastor Alemán',
  'Pastor Australiano',
  'Pastor Belga Malinois',
  'Pastor Blanco Suizo',
  'Pastor de Shetland',
  'Pastor Inglés',
  'Pequinés',
  'Perro de Agua Español',
  'Pinscher Miniatura',
  'Pitbull',
  'Pointer',
  'Pomerania',
  'Presa Canario',
  'Pug',
  'Rhodesian Ridgeback',
  'Rottweiler',
  'Samoyedo',
  'San Bernardo',
  'Schnauzer',
  'Schnauzer Gigante',
  'Schnauzer Miniatura',
  'Setter Irlandés',
  'Shar Pei',
  'Shiba Inu',
  'Shih Tzu',
  'Staffordshire Bull Terrier',
  'Terranova',
  'Vizsla',
  'Weimaraner',
  'West Highland White Terrier',
  'Whippet',
  'Yorkshire Terrier',
  'Otro',
];

export const CAT_BREEDS = [
  'Mestizo / Criollo',
  'No sé / No aplica',
  'Abisinio',
  'American Curl',
  'American Shorthair',
  'Angora',
  'Azul Ruso',
  'Balinés',
  'Bengalí',
  'Birmano',
  'Bobtail Japonés',
  'Bombay',
  'Bosque de Noruega',
  'British Shorthair',
  'Burmés',
  'Chartreux',
  'Cornish Rex',
  'Devon Rex',
  'Europeo Común',
  'Exótico de Pelo Corto',
  'Himalayo',
  'Korat',
  'Maine Coon',
  'Manx',
  'Mau Egipcio',
  'Munchkin',
  'Ocicat',
  'Oriental',
  'Persa',
  'Ragdoll',
  'Scottish Fold',
  'Selkirk Rex',
  'Siamés',
  'Siberiano',
  'Singapura',
  'Somalí',
  'Sphynx',
  'Tonkinés',
  'Van Turco',
  'Otro',
];
